### PR TITLE
Prepare for intended final 3.1 pre-release

### PR DESCRIPTION
**Pull request by gjsjohnmurray**
This PR prepares the documentation for the 3.1.2022092601 pre-release, which is planned for Monday as the final pre-release before we ship 3.2 as the new regular release on Marketplace.

@isc-bsaviano @isc-rsingh I also need approval for PR #160.

### CODE REVIEW

**Comment by isc-bsaviano** [comment]
@gjsjohnmurray This looks good but I'll approve it after #160 is merged

**Comment by gjsjohnmurray** [comment]
Setting as draft until updated after #160 merges.

**Comment by gjsjohnmurray** [comment]
As part of this PR I have established code formatting conventions and reformatted code to conform. The #160 changes have also been added.

Testable VSIX is at https://github.com/intersystems-community/intersystems-servermanager/suites/8511287775/artifacts/379105672

@isc-bsaviano please install this manually for a final sanity check, then approve the PR if you are happy with it.

**Comment by gjsjohnmurray** [comment]
> @isc-bsaviano please install this manually for a final sanity check, then approve the PR if you are happy with it.

Or @isc-rsingh

**Comment by isc-bsaviano** [comment]
@gjsjohnmurray I'm doing a quick sanity check now using this VSIX and the latest beta version off the main extension's prerelease branch. With a password that's stored in plain text, the main extension doesn't return it from `serverForUri()`, which forces the user to re-enter it into the authentication provider. When using the auth provider to store the password, things work well once the password is stored but that initial attempt when users need to create the server credentials wasn't flawless IMO. After giving the main extension permission and saving a password for the credentials, the main extension appeared to not use the credentials and still prompted me for a password using its own prompt. That needs to be cleaned up. Also, I need to make a fix in the language server that traps errors so it doesn't crash if the `getSession()` promise rejects.

**Review by isc-rsingh — APPROVED** [review]
My review is documentation only, and a sanity check installing and using it for the day.

**Comment by gjsjohnmurray** [comment]
@isc-bsaviano from what you write I'm not clear if you're finding something newly broken in this PR's VSIX compared to the latest pre-release of Server Manager currently installable from Marketplace. Nor if you think resolving those problems will need a change in SM, or only in the OS (pre-release) and LS extensions.

**Comment by isc-bsaviano** [comment]
@gjsjohnmurray Sorry, I just wanted to make sure that I mentioned these issues before release so they get fixed. I think this PR can be merged. I will tackle the LS issue now. Can you look into the main extension ones?

**Comment by gjsjohnmurray** [comment]
> Can you look into the main extension ones?

@isc-bsaviano please open issue(s) for them on the OS repo. I can't promise to look at them soon, but at least they'll have been captured.

Merging this now.

**Pull request merged**
