### PR TITLE
Authentication provider

### PR DESCRIPTION
**Pull request by gjsjohnmurray**
This implements an Authentication Provider for improved security.

Initially we will publish it as a pre-release, using the new mechanism introduced in VS Code 1.63.

Created as a draft PR to prevent merging until CI changes by @daimor are ready.

### CODE REVIEW

**Comment by isc-bsaviano** [comment]
@gjsjohnmurray How does this affect the other 2 extensions? Will the exported API still function the same way? I want to make sure I update the LS if it's required before this gets out

**Comment by gjsjohnmurray** [comment]
CI failure probably cause by us requiring 1.63 engine, which isn't yet released.

**Comment by gjsjohnmurray** [comment]
@isc-bsaviano my branch at https://github.com/gjsjohnmurray/vscode-objectscript/tree/authentication-provider contains the changes needed to make vscode-objectscript cope with the absence of credentials in the `getServerSpec` API response.

Ultimately the fragment of code which my OS branch uses to get the credentials could be released as an NPM package and included in extensions that need to do this, rather than copy-pasted.

When I checked the LS source it looked like LS doesn't get credentials directly from SM but instead uses a vscode-objectscript API.

In due course vscode-objectscript (OS) should probably be amended so it no longer shares over API the credentials it obtained using the `intersystems-server-credentials` authentication provider (AP) implemented in SM 3. This would force its API clients (e.g. LS) to use the AP themselves. That way the user gets to see exactly which extensions are accessing credentials. As things stand, trusting OS is a bit of a risk because OS can't restrict which extensions use its own APIs to get credentials.

**Comment by isc-bsaviano** [comment]
@gjsjohnmurray I will look at that branch and the LS code and see what I would need to do to avoid having the main extension export and API that returns passwords

**Comment by isc-bsaviano** [comment]
@gjsjohnmurray I added support for this in the Language Server in https://github.com/intersystems/language-server/commit/1f75e69165dbb7571d6a4f1755f65bc1ad617640

**Comment by daimor** [comment]
As I remember we switched to Windows builds due to some Windows-only dependencies, such as for Windows Registry. Will this feature keep working after that?

**Comment by gjsjohnmurray** [comment]
> As I remember we switched to Windows builds due to some Windows-only dependencies, such as for Windows Registry. Will this feature keep working after that?

@daimor you are correct. I had forgotten that. Thanks!

**Comment by gjsjohnmurray** [comment]
Closed in favour of #111

**Pull request closed without merging**
