### PR TITLE
Don't attempt to open the SMP in a Simple Browser for IRIS 2024.1+

### LINKED ISSUE #224: White page - VS Simple browser
Hello,

I followed instruction from this site https://intersystems-community.github.io/vscode-objectscript/extensionui/ to set up all /csp/sys/ WebApplication to AutoDetect cookies for session. 

When Im trying to open management portal within VS Code, I got blank white page. Is it something what do I need to set up as well and is not mentioned in documentation?

Thanks

### PR DESCRIPTION
**Pull request by isc-bsaviano**
This PR fixes #224

### CODE REVIEW

**Comment by gjsjohnmurray** [comment]
Doing that seems unfair on pre 2024.1 sites that have already got this working.

**Comment by isc-bsaviano** [comment]
I understand that some people might find this useful but I don't think that opening in an external browser is that much worse of a user experience. It's a shame that we didn't have advance notice of this change. I think that adding an IRIS version context key just to hide the button is too much work. I guess I can add another check to the Simple Browser-specific path but I don't like keeping features that only work on old versions. This is a modern/cutting edge tool; it seems wrong to me for it to have features that you have to be out of date to use.

**Comment by gjsjohnmurray** [comment]
I agree that retrofitting version info into the `contextValue` of the `TreeItem`s is more work than can be justified here, though there may be future cases where what we show on a tree node needs to take account of the server version.

However I'm unhappy with backward-incompatible changes, and resist us releasing a new version of Server Manager in which a feature that was being used successfully on pre-2024.1 servers suddenly vanishes in the interests of not confusing 2024.1+ users by offering something that a back-incompatible server-side change has rendered non-operational.

Please enhance this code to do the version check and advise the 2024.1+ user that the button they pressed is unable to work with their server level.

https://github.com/intersystems-community/intersystems-servermanager/blob/0fe86bf7be69ed199093ca2f60a0c4f3d712cd43/src/api/getPortalUriWithToken.ts#L50-L74

**Comment by isc-bsaviano** [comment]
I'll make that change for now but when IRIS versions 2024.1+ get more prevalent we will have to remove this button.

**Review by gjsjohnmurray — APPROVED** [review]

**Pull request merged**
