### PR TITLE
Prevent overprompting for permission and account

### LINKED ISSUE #242: Recent VS Code change has resulted in more frequent user account quickpicks
Recently (see https://code.visualstudio.com/updates/v1_93#_authentication-account-api) VS Code finalized some changes to the authentication API that has impacted how Server Manager's 'InterSystems Server Credentials' authentication provider behaves, resulting in users more frequently having to pick which credentials they want used.

For instance, expanding more than one server entry in the Server Manager tree results in unnecessary prompts asking:

image

despite this permission having previously been granted.

That dialog is followed by a quickpick in which the correct account is listed first and preselected, followed by accounts on unrelated servers, e.g.

image

This results in two extraneous "Enter" keypresses or mouse clicks being required.

I will update Server Manager and provide information about how consumers of its API (e.g. the ObjectScript extension) will need to be changed to solve the same issue in their own authentication pathways.

### PR DESCRIPTION
**Pull request by gjsjohnmurray**
This PR fixes #242

### CODE REVIEW

**Comment by gjsjohnmurray** [comment]
Steps required before merge and release:

- [ ] Bump ./types/package.json to 3.8.0
- [ ] From ./types run `npm publish --tag latest --access public` to publish @intersystems-community/intersystems-servermanager
- [ ] Update ./package.json `devDependencies` to use this

**Comment by gjsjohnmurray** [comment]
@isc-bsaviano please install this VSIX to verify that Server Manager continues working as normal but without the recently-appearing superfluous re-prompting for permission and for account.

That behaviour will continue in the ObjectScript extension and others using our authentication provider until we publish 3.8, they require it, and they tweak their calls (see updated README info).

**Comment by isc-bsaviano** [comment]
@gjsjohnmurray I don't use the auth provider in my regular workflows. What's the best workflow to test this?

**Comment by gjsjohnmurray** [comment]
I assume your `intersystems.servers` entries contain passwords alongside usernames. Please remove the password from one or more entries, then expand those servers to discover their namespaces. When prompted for a password, type it in and click the key icon on the input title. Then restart VS Code and re-expand those servers. Prior to this PR you would get reprompted to give permission and to confirm which account to use.

**Comment by isc-bsaviano** [comment]
@gjsjohnmurray The new VSIX seems fine to me. It works as intended, but since I don't use this on a day-to-day basis I've never experienced the problem that it's trying to solve.

**Review by isc-rsingh — APPROVED** [review]

**Pull request merged**
