### PR TITLE
Treat same username on different servers as distinct accounts (fix #194)

### LINKED ISSUE #194: Sign Out offers to delete stored password for multiple servers
> This solution has partially solved my issue, as indeed I can log out and be prompted to delete the password here. However, there's another problem.

image

> After clicking the link once, it not only asks whether to delete the password for the currently connected server but also for every account with the same name. I have more than 20 servers saved in the system, all with the same username, hence this dialogue box keeps popping up over 20 times. I need to carefully read the content of each pop-up to make sure I'm deleting the correct password.

_Originally posted by @hsyhhssyy in https://github.com/intersystems-community/intersystems-servermanager/issues/192#issuecomment-1650992172_

### PR DESCRIPTION
**Pull request by gjsjohnmurray**
This PR fixes #194.

Prior to this change, if user 'jdoe' has signed in to servers 'iris-1' and 'iris-2' there would be only one InterSystems Server Credential  entry for 'jdoe' in VS Code's Accounts context menu, and using the Sign Out action from its submenu would offer to delete stored 'jdoe' passwords for every server they existed for.

This change means 'jdoe on iris-1' and 'jdoe on iris-2' are treated as separate accounts.

### CODE REVIEW

**Comment by gjsjohnmurray** [comment]
@hsyhhssyy please download the zipped dev VSIX from https://github.com/intersystems-community/intersystems-servermanager/suites/14579768037/artifacts/825807469, unzip it and install it, for example by drag/dropping the extracted VSIX onto Extension view. Then see if account sign-out behaves better.

**Comment by gjsjohnmurray** [comment]
@isc-bsaviano please try [this dev VSIX](https://github.com/intersystems-community/intersystems-servermanager/suites/14585572037/artifacts/826225637) as a cross-check that the change doesn't break anything. I'll probably wait until we've heard from @hsyhhssyy before merging, in case changes turn out to be necessary.

**Comment by isc-bsaviano** [comment]
@gjsjohnmurray I just store my passwords in plaintext so I'll defer to the reporter to test this.

**Comment by hsyhhssyy** [comment]
@gjsjohnmurray 
I greatly appreciate your help. As I've mentioned in a comment on another issue, I've installed this plugin and it's functioning exactly as I had hoped.

**Pull request merged**
